-- AlterTable
ALTER TABLE "cards" ADD COLUMN     "art_crop_h" DOUBLE PRECISION NOT NULL DEFAULT 0.50,
ADD COLUMN     "art_crop_w" DOUBLE PRECISION NOT NULL DEFAULT 0.86,
ADD COLUMN     "art_crop_x" DOUBLE PRECISION NOT NULL DEFAULT 0.07,
ADD COLUMN     "art_crop_y" DOUBLE PRECISION NOT NULL DEFAULT 0.11;

